spring.application.name=spring_mvc_study1_mvc

# ?? LEVEL:
# TRACE > DEBUG > INFO > WARN > ERROR
# trace? ?? ?, trace, debug, info, warn, error ??? ?? ??
# debug? ?? ?, debug, info, warn, error ????? ??
# ?? ?? ????? trace, ?? ????? debug, ?? ????? info ??
logging.level.com.example.spring_mvc_study1_mvc=debug

#?? root ????? ?? ?? ??(default ?? info?)
logging.level.root=info